apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: m321
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: agachan/lb321-user:v1
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"  # Set a CPU request value (200 millicores)
            limits:
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: m321
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
